[env]
term = "xterm-256color"

[general]
import=[
"~/.config/alacritty/onedark.toml",
]

[font.normal]
family="AdwaitaMono Nerd Font Mono"

[font.bold]
family="AdwaitaMono Nerd Font Mono"
style="bold"

[cursor]
style.shape = "Beam"

[keyboard]
bindings = [
  {key="Backspace", mods="Control", chars="\u0017"},
]
