[colors.primary]
background="#282C34"
foreground="#ABB2BF"

[colors.normal]
black="#282C34"
red="#e06c75"
green="#98c379"
blue="#61afef"
magenta="#c678dd"
cyan="#56c6b2"
white="#ABB2BF"

[colors.bright]
black="#5C6370"
red="#e06c75"
green="#98c379"
blue="#61afef"
magenta="#c678dd"
cyan="#56c6b2"
white="#ABB2BF"
